const EXT_COLORS = {
  py: '#3b82f6',
  js: '#f59e0b',
  ts: '#2563eb',
  jsx: '#06b6d4',
  tsx: '#06b6d4',
  md: '#8b5cf6',
  csv: '#10b981',
  json: '#f97316',
  txt: '#6b7280',
  html: '#ef4444',
  css: '#ec4899',
}

function extColor(ext) {
  return EXT_COLORS[ext?.toLowerCase()] || '#7c3aed'
}

function formatSize(bytes) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function fileIcon(ext) {
  const icons = {
    py: '🐍', js: '🟨', ts: '🔷', jsx: '⚛️', tsx: '⚛️',
    md: '📝', csv: '📊', json: '📋', txt: '📄', html: '🌐',
    css: '🎨',
  }
  return icons[ext?.toLowerCase()] || '📁'
}

export default function OutputPanel({ files, sessionId, collapsed, onToggleCollapse }) {
  function handleDownload(filename) {
    const url = `/files/${sessionId}/${filename}`
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
  }

  return (
    <aside className={`output-panel ${collapsed ? 'collapsed' : ''}`}>
      <div className="panel-header">
        <span className="panel-title">📁 Generated Files</span>
        <button className="icon-btn" onClick={onToggleCollapse} title="Hide panel">
          ›
        </button>
      </div>

      <div className="file-list">
        {files.length === 0 ? (
          <div className="no-files">
            <div className="no-files-icon">📂</div>
            <p>Files generated by the agent will appear here for download.</p>
          </div>
        ) : (
          files.map((f) => (
            <div key={f.name} className="file-card">
              <div className="file-card-header">
                <span style={{ fontSize: 16 }}>{fileIcon(f.ext)}</span>
                <span
                  className="file-ext-badge"
                  style={{ background: extColor(f.ext) }}
                >
                  {f.ext || 'file'}
                </span>
                <span className="file-name" title={f.name}>{f.name}</span>
              </div>
              <div
                style={{
                  padding: '7px 12px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: 8,
                }}
              >
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                  {formatSize(f.size)}
                </span>
                <button
                  className="download-btn"
                  onClick={() => handleDownload(f.name)}
                >
                  ⬇ Download
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </aside>
  )
}
